AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  VPCId:
    Type: String

Resources:

  nodejsSecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/asmir-cloudformation-bucket/stacks/nodejs-security.groups.yml" #required