AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  ImageId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    AllowedValues: 
      - t2.micro
      - t2.medium
      - t2.large

  KeyName:
    Type: String

  VPCId:
    Type: String

  Subnets:
    Type: CommaDelimitedList

  GithubUsername:
    Type: String

  GithubPersonalAccessToken:
    Type: String

  GithubRepositoryName:
    Type: String

  GithubBranch:
    Type: String

Resources:

  nodejsSecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCId: !Ref VPCId
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-security-groups.yml" #required

  nodejsRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        nodejsS3bucket: asmir-cloudformation-bucket
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-roles.yml" #required