AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  VPCId:
    Type: String
  
  nodejsS3:
    Type: String

Resources:

  nodejsCreateS3BucketAndSNS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        nodejsS3: !Ref nodejsS3
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-S3-and-SNS.yml"

  nodejsSecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCId: !Ref VPCId
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-security-groups.yml" #required

  nodejsRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        nodejsS3: !Ref nodejsS3
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-roles.yml" #required