AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  VPCId:
    Type: String

Resources:

  nodejsSecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://codepipeline-eu-west-2-692454310004.s3.amazonaws.com/stacks/nodejs-security-groups.yml #required
      Parameters: 
        VPCId : !Ref VPCId
  