AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  nodejsS3:
    Type: String
    
Resources:

# ROLE FOR EC2

  nodejsRoleForEC2:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Path: /
      RoleName: nodejsRoleForEC2
      Tags:
        - Key: Costs
          Value: intern

# INSTANCE PROFILE FOR EC2

  nodejsInstanceProfileForEC2:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles: [ !Ref nodejsRoleForEC2 ]

# ROLE FOR CODE BUILD

  nodejsRoleForCodeBuild:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: "Allows CodeBuild to call AWS services on your behalf."
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Path: /
      RoleName: nodejsRoleForCodeBuild
      Policies:
        - PolicyName: codebuildS3policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: [ !Sub 'arn:aws:s3:::${nodejsS3}', 'arn:aws:s3:::*/*', 'arn:aws:s3:*:*:job/*' ]
      Tags:
        - Key: Costs
          Value: intern

# ROLE FOR CODE DEPLOY

  nodejsRoleForCodeDeploy:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Sid: ""
            Principal:
              Service:
              - "codedeploy.us-west-1.amazonaws.com"
              - "codedeploy.eu-west-3.amazonaws.com"
              - "codedeploy.eu-west-2.amazonaws.com"
              - "codedeploy.sa-east-1.amazonaws.com"
              - "codedeploy.us-west-2.amazonaws.com"
              - "codedeploy.ap-northeast-2.amazonaws.com"
              - "codedeploy.us-east-2.amazonaws.com"
              - "codedeploy.eu-west-1.amazonaws.com"
              - "codedeploy.ap-southeast-1.amazonaws.com"
              - "codedeploy.ap-south-1.amazonaws.com"
              - "codedeploy.eu-central-1.amazonaws.com"
              - "codedeploy.ap-northeast-1.amazonaws.com"
              - "codedeploy.ap-east-1.amazonaws.com"
              - "codedeploy.us-east-1.amazonaws.com"
              - "codedeploy.ap-southeast-2.amazonaws.com"
              - "codedeploy.ca-central-1.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: "Allows CodeDeploy to call AWS services on your behalf."
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AutoScalingFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
      Path: /
      RoleName: nodejsRoleForCodeDeploy
      Policies:
        - PolicyName: codedepoloyS3policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: [ !Sub 'arn:aws:s3:::${nodejsS3}', 'arn:aws:s3:::*/*', 'arn:aws:s3:*:*:job/*' ]
      Tags:
        - Key: Costs
          Value: intern

# ROLE FOR CODE PIPELINE

  nodejsRoleForCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Description: Allows CodePipeline to call AWS services on your behalf.
      RoleName: nodejsRoleForCodePipeline
      Policies:
        - PolicyName: CloudPipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "cloudformation:*"
                Resource: "*"
              - Effect: Allow
                Action: "codebuild:*"
                Resource: "*"
              - Effect: Allow
                Action: "codedeploy:*"
                Resource: "*"
              - Effect: Allow
                Action: "sns:Publish"
                Resource: "*"
              - Effect: Allow
                Action: s3:*
                Resource: [ !Sub 'arn:aws:s3:::${nodejsS3}', 'arn:aws:s3:::*/*', 'arn:aws:s3:*:*:job/*' ]
              - Effect: Allow
                Action: "ec2:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"

Outputs:

  nodejsInstanceProfileForEC2:
    Value: !Ref nodejsInstanceProfileForEC2
    Export:
      Name: !Sub base-nodejsInstanceProfileForEC2

  nodejsRoleForCodeBuild:
    Value: !Ref nodejsRoleForCodeBuild
    Export:
      Name: !Sub base-nodejsRoleForCodeBuild

  nodejsRoleForCodeDeploy:
    Value: !Ref nodejsRoleForCodeDeploy
    Export:
      Name: !Sub base-nodejsRoleForCodeDeploy

  nodejsRoleForCodePipeline:
    Value: !Ref nodejsRoleForCodePipeline
    Export:
      Name: !Sub base-nodejsRoleForCodePipeline