AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  Prefix: 
    Type: String

  Environment:
    Type: String
    
Resources:

  nodejsApigateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${Prefix}-${Environment}-apigateway

  nodejsApigatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !GetAtt nodejsApigateway.RootResourceId #required
      PathPart: lottery #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsApigatewayMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET #required
      Integration:
        IntegrationResponses: 
          - StatusCode: "200"
        Uri: "http://nodejsApplicationLoadbalancer-472309917.eu-west-2.elb.amazonaws.com/lottery"
      MethodResponses:
        - ResponseModels: 
            message : "hjgjh"
          StatusCode: "200"
      ResourceId: !Ref nodejsApigatewayResource #required
      RestApiId: !Ref nodejsApigateway #required
  
  