AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  DBName:
    Type: String

  DBMasterUserPassword:
    Type: String

  DBMasterUsername:
    Type: String

  SecurityGroup:
    Type: String

Resources:

  RDSDBParameterGroup: 
    Properties: 
      Description: "CloudFormation Sample Parameter Group"
      Family: mysql5.7
      Parameters: 
        sql_mode: IGNORE_SPACE
    Type: "AWS::RDS::DBParameterGroup"

  nodejsRDS:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t2.micro #required
      DBInstanceIdentifier: !Sub nodejs-${AWS::StackName}-db
      DBParameterGroupName: !Ref RDSDBParameterGroup
      DBName: !Ref DBName
      DeleteAutomatedBackups: true
      DeletionProtection: false
      Engine: MySQL
      EngineVersion: "5.7.22"
      MasterUserPassword: !Ref DBMasterUserPassword
      MasterUsername: !Ref DBMasterUsername
      Port: "3306"
      PubliclyAccessible: false
      SourceRegion: !Ref AWS::Region
      Tags:
        - Key: Costs
          Value: intern
      VPCSecurityGroups:
        - Ref: SecurityGroup

  
        
Outputs:

  nodejsRDS:
    Value: !Ref nodejsRDS
    Export:
      Name: infrastructure-nodejsRDS