AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  Prefix: 
    Type: String

  Environment:
    Type: String

  GithubUsername:
    Type: String

  GithubPersonalAccessToken:
    Type: String

  GithubRepositoryName:
    Type: String

  GithubBranch:
    Type: String

  nodejsS3:
    Type: String

  autoscaling:
    Type: String

Resources:

# CODE BUILD PROJECT

  nodejsCodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Source:
        Type: S3
        Location: !Sub ${nodejsS3}/SourceOutput
      Name: nodejs-CodeBuild
      Artifacts:
          Location: !Ref nodejsS3
          Name: "/"
          Path: BuildOutput
          NamespaceType: BUILD_ID
          Type: S3
      ServiceRole: 
        Fn::ImportValue: !Sub ${Prefix}-${Environment}-RoleForCodeBuild
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        Type: LINUX_CONTAINER

# CODE DEPLOY APPLICATION

  nodejsCodeDeployApplication:
    Type: "AWS::CodeDeploy::Application"
    Properties:
      ApplicationName: nodejs
      ComputePlatform: Server

# CODE DEPLOY - DEPLOYMENT GROUP

  nodejsCodeDeployDeploymentGroup:
    Type: "AWS::CodeDeploy::DeploymentGroup"
    Properties:
      ApplicationName: !Ref "nodejsCodeDeployApplication"
      AutoScalingGroups:
        - !Ref autoscaling
      DeploymentGroupName: "nodejsDeploymentGroup"
      ServiceRoleArn: 
        Fn::ImportValue: !Sub ${Prefix}-${Environment}-RoleForCodeDeploy
  
# CODEPIPELINE

  nodejsCodepipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Type: S3 
        Location: !Ref nodejsS3
      Name: nodejsCodepipeline
      RestartExecutionOnUpdate: true
      RoleArn: 
        Fn::ImportValue: !Sub ${Prefix}-${Environment}-RoleForCodePipeline
      Stages:
        - Name: GetSource
          Actions:
            - Name: SourceAction
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1 
                Provider: GitHub 
              OutputArtifacts:
                - Name: SourceOutput 
              Region: !Ref "AWS::Region"
              Configuration:
                Owner: !Ref "GithubUsername"
                Repo: !Ref "GithubRepositoryName"
                Branch: !Ref "GithubBranch"
                PollForSourceChanges: true
                OAuthToken: !Ref "GithubPersonalAccessToken"
              RunOrder: 1 
        - Name: Build 
          Actions: 
            - Name: BuildProject 
              InputArtifacts: 
                - Name: SourceOutput 
              ActionTypeId: 
                Category: Build
                Owner: AWS 
                Version: 1 
                Provider: CodeBuild
              Configuration: 
                ProjectName: !Ref "nodejsCodeBuild"
              OutputArtifacts:
                - Name: BuildOutput 
              RunOrder: 2 
        - Name: Approval 
          Actions: 
            - Name: ManualApproval
              ActionTypeId: 
                Category: Approval
                Owner: AWS 
                Version: 1 
                Provider: Manual
              Configuration:
                NotificationArn: 
                  Fn::ImportValue: !Sub ${Prefix}-${Environment}-SNStopicForManualApproval
              RunOrder: 3
        - Name: Deploy 
          Actions: 
            - Name: DeployProject 
              InputArtifacts: 
                - Name: BuildOutput 
              ActionTypeId: 
                Category: Deploy
                Owner: AWS 
                Version: 1 
                Provider: CodeDeploy
              Configuration: 
                ApplicationName: !Ref "nodejsCodeDeployApplication"
                DeploymentGroupName: !Ref "nodejsCodeDeployDeploymentGroup"