AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  DBName:
    Type: String

  DBMasterUserPassword:
    Type: String

  DBMasterUsername:
    Type: String

  SecurityGroup:
    Type: String

Resources:

  nodejsRDS:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t2.micro #required
      DBInstanceIdentifier: !Sub nodejs-${AWS::StackName}-db
      DBName: !Ref DBName
      DBParameterGroupName: String
      DBSecurityGroups:
        - Ref: SecurityGroup
      DeleteAutomatedBackups: true
      DeletionProtection: false
      Engine: MySQL
      EngineVersion: "MySQL 5.7.22"
      MasterUserPassword: !Ref DBMasterUserPassword
      MasterUsername: !Ref DBMasterUsername
      Port: "3306"
      PubliclyAccessible: false
      Tags:
        - Key: Costs
          Value: intern

  
        
Outputs:

  nodejsRDS:
    Value: !Ref nodejsRDS
    Export:
      Name: infrastructure-nodejsRDS