AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  Prefix: 
    Type: String

  Environment:
    Type: String
    
Resources:

  nodejsApigateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${Prefix}-${Environment}-apigateway

  nodejsApigatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !GetAtt nodejsApigateway.RootResourceId #required
      PathPart: lottery #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsApigatewayMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET #required
      Integration:
        IntegrationResponses: 
          - StatusCode: "200"
            ResponseTemplates: {"application/json": "$input.json('$.body')"}
        IntegrationHttpMethod: GET
        Type: HTTP
        Uri: "http://nodejsApplicationLoadbalancer-472309917.eu-west-2.elb.amazonaws.com/lottery"
      MethodResponses:
        - StatusCode: "200"
          ResponseModels: !Ref nodejsGetMethodModel
      ResourceId: !Ref nodejsApigatewayResource #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsGetMethodModel:
    Type: AWS::ApiGateway::Model
    Properties: 
      ContentType: application/json=
      Name: GetModel
      RestApiId: !Ref nodejsApigateway
      Schema: 
        $schema: http://json-schema.org/draft-04/schema#
        title: Empty Schema
        type: object
  
  