AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  Prefix: 
    Type: String

  Environment:
    Type: String
    
Resources:

  nodejsGetMethodModel:
    Type: AWS::ApiGateway::Model
    Properties: 
      ContentType: application/json
      Name: ResponseModel
      RestApiId: !Ref nodejsApigateway
      Schema: 
        $schema: http://json-schema.org/draft-04/schema#
        title: Empty Schema
        type: object
  
  nodejsErrorModel:
    Type: AWS::ApiGateway::Model
    Properties: 
      ContentType: application/json
      Name: ErrorModel
      RestApiId: !Ref nodejsApigateway
      Schema: 
        $schema: http://json-schema.org/draft-04/schema#
        title: Error Schema
        type: object
        properties:
          message:
            type: string

  nodejsApigateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${Prefix}-${Environment}-apigateway

  nodejsApigatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !GetAtt nodejsApigateway.RootResourceId #required
      PathPart: lottery #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsApigatewayMethodGet:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET #required
      Integration:
        IntegrationResponses: 
          - StatusCode: "200"
            ResponseTemplates: {"application/json": ""}
        IntegrationHttpMethod: GET
        Type: HTTP
        Uri: "http://nodejsApplicationLoadbalancer-472309917.eu-west-2.elb.amazonaws.com/lottery"
      MethodResponses:
        - StatusCode: "200"
          ResponseModels: 
            application/json: !Ref nodejsGetMethodModel
      ResourceId: !Ref nodejsApigatewayResource #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsApigatewayMethodPost:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST #required
      Integration:
        IntegrationResponses: 
          - StatusCode: "200"
            ResponseTemplates: {"application/json": ""}
        IntegrationHttpMethod: POST
        Type: HTTP
        Uri: "http://nodejsApplicationLoadbalancer-472309917.eu-west-2.elb.amazonaws.com/lottery"
      MethodResponses:
        - StatusCode: "200"
          ResponseModels: 
            application/json: !Ref nodejsGetMethodModel
      ResourceId: !Ref nodejsApigatewayResource #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsApigatewayResourceGetById:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref nodejsApigatewayResource #required
      PathPart: "{id}" #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsApigatewayMethodGetbyID:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET #required
      Integration:
        IntegrationResponses: 
          - StatusCode: "200"
            ResponseTemplates: {"application/json": ""}
          - StatusCode: "404"
            SelectionPattern: "404"
            ResponseTemplates: {"application/json": "Glup si"}
        IntegrationHttpMethod: GET
        Type: HTTP
        Uri: "http://nodejsApplicationLoadbalancer-472309917.eu-west-2.elb.amazonaws.com/lottery"
      MethodResponses:
        - StatusCode: "200"
          ResponseModels: 
            application/json: !Ref nodejsGetMethodModel
        - StatusCode: "404"
          ResponseModels: 
            application/json: !Ref nodejsGetMethodModel
      ResourceId: !Ref nodejsApigatewayResourceGetById #required
      RestApiId: !Ref nodejsApigateway #required

  nodejsApigatewayMethodPutbyID:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST #required
      Integration:
        IntegrationResponses: 
          - StatusCode: "200"
            ResponseTemplates: {"application/json": ""}
        IntegrationHttpMethod: POST
        Type: HTTP
        Uri: "http://nodejsApplicationLoadbalancer-472309917.eu-west-2.elb.amazonaws.com/lottery"
      MethodResponses:
        - StatusCode: "200"
          ResponseModels: 
            application/json: !Ref nodejsGetMethodModel
      ResourceId: !Ref nodejsApigatewayResourceGetById #required
      RestApiId: !Ref nodejsApigateway #required
  