AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  ImageId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    AllowedValues: 
      - t2.micro
      - t2.medium
      - t2.large

  KeyName:
    Type: String

  VPCId:
    Type: String

  Subnets:
    Type: CommaDelimitedList

  GithubUsername:
    Type: String

  GithubRepositoryName:
    Type: String

  GithubBranch:
    Type: String

  Evnironment:
    Type: String

Resources:

  nodejsALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Subnet1: !Select [ 0, !Ref Subnets ] 
        Subnet2: !Select [ 1, !Ref Subnets ] 
        Subnet3: !Select [ 2, !Ref Subnets ] 
        VPCId: !Ref VPCId
      TemplateURL: "https://awso-production-cloudformation-bucket.s3.eu-west-2.amazonaws.com/stacks/nodejs-alb.yml" #required
    
  nodejsASG:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        Evnironment: !Ref Evnironment
        TargetGroup: !GetAtt nodejsALB.Outputs.nodejsTargetGroup
        NameDB: !ImportValue 'awso-production-DBName'
        UsernameDB: !Join ['', ['{{resolve:secretsmanager:', !ImportValue 'awso-production-secretsRDS', ':SecretString:username}}' ]]
        PasswordDB: !Join ['', ['{{resolve:secretsmanager:', !ImportValue 'awso-production-secretsRDS', ':SecretString:password}}' ]]
        HostDB: !ImportValue 'awso-production-nodejsRDSendpoint'
        PortDB: !ImportValue 'awso-production-nodejsRDSport'
        DialectDB: !Join ['', ['{{resolve:secretsmanager:', !ImportValue 'awso-production-secretsRDS', ':SecretString:engine}}' ]]
      TemplateURL: "https://awso-production-cloudformation-bucket.s3.eu-west-2.amazonaws.com/stacks/nodejs-asg.yml" #required
  
  nodejsPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        GithubUsername: !Ref GithubUsername 
        GithubPersonalAccessToken: !Join ['', ['{{resolve:secretsmanager:', !ImportValue 'awso-production-MySecretB', ':SecretString:token}}' ]] 
        GithubRepositoryName: !Ref GithubRepositoryName 
        GithubBranch: !Ref GithubBranch 
        nodejsS3: !ImportValue awso-production-nodejsS3bucket 
        autoscaling: !GetAtt nodejsASG.Outputs.nodejsAutoScalingGroup
      TemplateURL: "https://awso-production-cloudformation-bucket.s3.eu-west-2.amazonaws.com/stacks/nodejs-codepipeline.yml" #required
  