AWSTemplateFormatVersion: "2010-09-09"
Description: Security groups for nodeJS

Parameters:

  ImageId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    AllowedValues: 
      - t2.micro
      - t2.medium
      - t2.large

  KeyName:
    Type: String

  VPCId:
    Type: String

  Subnets:
    Type: CommaDelimitedList

  GithubUsername:
    Type: String

  GithubPersonalAccessToken:
    Type: String

  GithubRepositoryName:
    Type: String

  GithubBranch:
    Type: String

  nodejsS3:
    Type: String

  Evnironment:
    Type: String

Resources:

  nodejsALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Subnet1: !Select [ 0, !Ref Subnets ] 
        Subnet2: !Select [ 1, !Ref Subnets ] 
        Subnet3: !Select [ 2, !Ref Subnets ] 
        VPCId: !Ref VPCId
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-alb.yml" #required
    
  nodejsASG:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        Evnironment: !Ref Evnironment
        UsernameDB: !Join ['', ['{{resolve:secretsmanager:', 'arn:aws:secretsmanager:eu-west-2:743584032881:secret:dbConnection-DwbMbw', ':SecretString:username}}' ]]
        PasswordDB: !Join ['', ['{{resolve:secretsmanager:', 'arn:aws:secretsmanager:eu-west-2:743584032881:secret:dbConnection-DwbMbw', ':SecretString:password}}' ]]
        NameDB: !Join ['', ['{{resolve:secretsmanager:', 'arn:aws:secretsmanager:eu-west-2:743584032881:secret:dbConnection-DwbMbw', ':SecretString:dbname}}' ]]
        HostDB: !Join ['', ['{{resolve:secretsmanager:', 'arn:aws:secretsmanager:eu-west-2:743584032881:secret:dbConnection-DwbMbw', ':SecretString:host}}' ]]
        PortDB: !Join ['', ['{{resolve:secretsmanager:', 'arn:aws:secretsmanager:eu-west-2:743584032881:secret:dbConnection-DwbMbw', ':SecretString:port}}' ]]
        DialectDB: !Join ['', ['{{resolve:secretsmanager:', 'arn:aws:secretsmanager:eu-west-2:743584032881:secret:dbConnection-DwbMbw', ':SecretString:engine}}' ]]
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-asg.yml" #required
  
  nodejsPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        GithubUsername: !Ref GithubUsername 
        GithubPersonalAccessToken: !Ref GithubPersonalAccessToken 
        GithubRepositoryName: !Ref GithubRepositoryName 
        GithubBranch: !Ref GithubBranch 
        nodejsS3: !Ref nodejsS3 
      TemplateURL: "https://asmir-cloudformation-bucket.s3.eu-west-2.amazonaws.com/Stacks/stacks/nodejs-codepipeline.yml" #required
  